#!/bin/bash

if ! [ -n "$_BASHRC_INIT" ]; then
  export _BASHRC_INIT="True"
elif [ "${TERM_PROGRAM}" == "vscode" ]; then
  >&2 echo "${TERM_PROGRAM} initialising shell"
else
  >&2 echo "Already Initialising bashrc"
  return
fi
>&2 echo "Initialising bashrc"
unset name_
# BASHRC START

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# If set, extended glob patterns will be used for paths and file names
shopt -s extglob

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ -f ~/.rc ]; then
  source ~/.rc
fi

test -e "/sandbox/$USER/tools/miniconda3/bin/conda" &&
eval "$(/sandbox/$USER/tools/miniconda3/bin/conda shell.bash hook 2>/dev/null)"
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/sandbox/$USER/tools/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/sandbox/$USER/tools/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/sandbox/$USER/tools/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/sandbox/$USER/tools/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Conda Block - Personalised
checkt conda &&
  load_env_file conda.sh


if [ "$color_prompt" = yes ]; then
    if [[ "${_USER_NAME}" != "" ]]; then
      _USER_NAME=$(echo "${_USER_NAME}" | tr '[:upper:]' '[:lower:]' )
      PS1="\${debian_chroot:+(\$debian_chroot)}\\[\\033[01;32m\\]${_USER_NAME}@${_HOST_NAME}\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\\$ "
      PS1_VAR='\${debian_chroot:+(\$debian_chroot)}\\[\\033[01;32m\\]${_USER_NAME}@${_HOST_NAME}\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\\$ '
    else
      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    fi
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    PS1_VAR='\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]'"${PS1_VAR}"
    ;;
*)
    ;;
esac

# Save the original prompt layout
export PS1_BASE="${PS1}"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

export PROMPT_DIRTRIM=2

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# More ls aliases can be found in aliases env file

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

# if test -z "${VSCODE_GIT_ASKPASS_NODE}"; then
#   _vs_code_paths=$(ls $HOME/.vscode-server/bin/*/bin/remote-cli/code 2>/dev/null)
#   path_count=$(echo $_vs_code_paths | wc -l)
#   if [ $path_count -eq 1 ]; then
#     _path=$(echo "$_vs_code_paths" | sed -E 's#/code\*?$##')
#     1>&2 echo "adding '$_path'"
#     export PATH="${_path}:${PATH}"
#   elif [ $path_count -gt 1 ]; then
#     # work out which one to select
#     1>&2 echo -e "\e[32mAdd the appropriate path below. \e[0m"
#     echo "$_vs_code_paths" | sed -E 's/(.*)code\*?/export PATH="\1:\$\{PATH\}"/'
#     continue
#   else
#     1>&2 echo -e "\e[34mWARNING: \`code\` not in PATH\e[0m"
#   fi
# fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


if [ -z "${_INIT_DIR}" ] \
  && [ "${TERM_PROGRAM}" != "vscode" ] \
  && [ -d "/sandbox/${USER}" ]; then
  cd "/sandbox/${USER}"
  _INIT_DIR="Done"
fi

# Use original cd path completion
# complete -r cd

# BASHRC END
test -n "${ENV_DEBUG}" &&
  >&2 echo -e "\tbashrc is Initialised"
unset _BASHRC_INIT
