
# _color_pre="\e["
# _color_end="m"

_color_reset="\e[0m"

# _color_fg="\e[38;5;"
# _color_bg="\e[48;5;"

# Foreground Colours
_black="\e[30m"
_red="\e[31m"
_green="\e[32m"
_yellow="\e[33m"
_blue="\e[34m"
_magenta="\e[35m"
_cyan="\e[36m"
_white="\e[37m"
_b_black="\e[90m"
_b_red="\e[91m"
_b_green="\e[92m"
_b_yellow="\e[93m"
_b_blue="\e[94m"
_b_magenta="\e[95m"
_b_cyan="\e[96m"
_b_white="\e[97m"

# Background Colours
_black_bg="\e[40m"
_red_bg="\e[41m"
_green_bg="\e[42m"
_yellow_bg="\e[43m"
_blue_bg="\e[44m"
_magenta_bg="\e[45m"
_cyan_bg="\e[46m"
_white_bg="\e[47m"
_b_black_bg="\e[100m"
_b_red_bg="\e[101m"
_b_green_bg="\e[102m"
_b_yellow_bg="\e[103m"
_b_blue_bg="\e[104m"
_b_magenta_bg="\e[105m"
_b_cyan_bg="\e[106m"
_b_white_bg="\e[107m"

# Other Formatting
_bold="\e[1m"
_dim="\e[2m"
_uline="\e[4m"
_blink="\e[5m"
_roloc="\e[7m"
_hidden="\e[8m"

_bold_off="\e[21m"
_dim_off="\e[22m"
_uline_off="\e[24m"
_blink_off="\e[25m"
_roloc_off="\e[27m"t
_hidden_off="\e[28m"

export BLACK="$_black"
export RED="$_red"
export GREEN="$_green"
export YELLOW="$_yellow"
export BLUE="$_blue"
export MAGENTA="$_magenta"
export CYAN="$_cyan"
export NO_COLOR="$_color_reset"