#!/bin/sh
name_="rc"
if ! [ -n "${_RC_INIT}" ]; then
  export _RC_INIT="True"
else
  >&2 echo "Already Initialising rc"
  exit
fi
>&2 echo "Initialising rc"
unset name_
# RC START
# This is for interactive shells

# Initialise Environment Tools
test -z "${ENV_REPO}" &&
  export ENV_REPO=$(dirname $(readlink -f "$0" 2>/dev/null ))
source "${ENV_REPO}/env.sh"

_USER_NAME=$( echo -n "$USER" | tr '[:upper:]' '[:lower:]' |  tr ' ' '-' )
_HOST_NAME="${HOST}"
test -z "${_HOST_NAME}" && _HOST_NAME="${HOSTNAME}" # Only one should exist

case "$_HOST_NAME" in
  *MacBook-*)
    _HOST_NAME="$(echo "${_HOST_NAME}" | sed -E 's/MacBook-(\w*)-(\d*)-?/MB-\1-\2/')"
  ;;
  DESKTOP-)
    _HOST_NAME="$(echo "${_HOST_NAME}" | sed -E 's/DESKTOP-*/WIN-')"
  ;;
  *)
  ;;
esac
_HOST_NAME="$(echo "${_HOST_NAME}" | sed -E 's/\.local$//')"

case "$_USER_NAME" in
  unknown*)
    _USER_NAME="unknown"
  ;;
  root)
    _USER_NAME="root"
  ;;
  *.*)
    _USER_NAME="$(
      echo "$_USER_NAME" |
      sed -E 's/^\W*(\w+)/\1/'
    )"
  ;;
  *)
    # First word -> first 7 characters
    _USER_NAME="$(
      echo "$_USER_NAME" |
      sed -E -e 's/^\W*(\w+)(\W.*)?//' \
      -e 's/(.{7}).*/\1/'
    )"
  ;;
esac

export _HOST_NAME
export _USER_NAME

OS_NAME=$(uname | lower )
if [[ "$OS_NAME" == "darwin"* ]] ; then
  quiet which sw_vers &&
    OS_NAME=$(sw_vers -productName | lower )
fi
export OS_NAME

case "$OS_NAME" in
  macos*)
    test -f "${ENV_REPO}/macos.sh" && source "${ENV_REPO}/macos.sh"
  ;;
  linux*)
    test -f "${ENV_REPO}/linux.sh" && source "${ENV_REPO}/linux.sh"
  ;;
  *)
    echo "OS:$OS_NAME has no env preferences" 1>&2
  ;;
esac

load_env_file data/vars.rc
load_env_file aliases
load_env_file tools.sh
load_env_file colors.sh


# RC END
test -n "${ENV_DEBUG}" &&
  >&2 echo -e "\trc is Initialised"
unset _RC_INIT
