#!/bin/zsh
name_="zprofile"
if ! [ -n "${_ZPROFILE_INIT}" ]; then
  export _ZPROFILE_INIT="True"
else
  >&2 echo "Already Initialising $name_"
  return
fi
>&2 echo "Initialising $name_"
unset name_
# ZSH PROFILE START

setopt extended_glob
setopt extendedglob

export ENV_REPO=$(dirname $(readlink -f "$0" 2>/dev/null))
test -f "${ENV_REPO}/profile" && source "${ENV_REPO}/profile"

# ZSH PROFILE END
test -n "${ENV_DEBUG}" &&
  >&2 echo -e "\tzprofile is Initialised"
unset _ZPROFILE_INIT
